local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local Workspace = game:GetService("Workspace")

local failures = 0
local success = 0

local function t(f)
    local ok, r = pcall(f)
    if ok and r then
        success += 1
    else
        failures += 1
    end
end

t(function() return game ~= nil end)
t(function() return workspace ~= nil end)
t(function() return Workspace:IsA("Workspace") end)
t(function() return Players ~= nil end)
t(function() return Players.LocalPlayer ~= nil end)
t(function() return RunService:IsClient() end)
t(function() return not RunService:IsServer() end)
t(function() return typeof(Vector3.new()) == "Vector3" end)
t(function() return typeof(Vector2.new()) == "Vector2" end)
t(function() return typeof(CFrame.new()) == "CFrame" end)
t(function() return typeof(UDim2.new()) == "UDim2" end)
t(function() return typeof(Color3.new()) == "Color3" end)
t(function() return Instance.new("Part") ~= nil end)
t(function() return math.floor(1.9) == 1 end)
t(function() return math.ceil(1.1) == 2 end)
t(function() return math.abs(-10) == 10 end)
t(function() return math.max(1,2,3) == 3 end)
t(function() return math.min(1,2,3) == 1 end)
t(function() return math.sqrt(16) == 4 end)
t(function() return math.pi > 3.14 and math.pi < 3.15 end)
t(function() return string.len("hello") == 5 end)
t(function() return string.sub("hello",1,2) == "he" end)
t(function() return string.rep("ab",2) == "abab" end)
t(function() return string.reverse("abc") == "cba" end)
t(function() return string.upper("a") == "A" end)
t(function() return string.lower("A") == "a" end)
t(function() return table.concat({"a","b","c"}) == "abc" end)
t(function() return table.insert({1,2,3},4) ~= nil end)
t(function() return table.remove({1,2,3},1) == 1 end)
t(function() return table.sort({3,2,1}) == nil end)
t(function() return pcall(function() error("x") end) end)
t(function() return type(pcall) == "function" end)
t(function() return type(xpcall) == "function" end)
t(function() return coroutine.create(function() end) ~= nil end)
t(function() return coroutine.resume(coroutine.create(function() end)) end)
t(function() return select("#",1,2,3) == 3 end)
t(function() return typeof(game:GetService("Players")) == "Instance" end)
t(function() return game:GetService("ReplicatedStorage") ~= nil end)
t(function() return game:GetService("Lighting") ~= nil end)
t(function() return workspace.CurrentCamera ~= nil end)
t(function() return typeof(workspace.CurrentCamera.CFrame) == "CFrame" end)
t(function() return typeof(workspace.CurrentCamera.ViewportSize) == "Vector2" end)
t(function() return os.time() > 0 end)
t(function() return os.clock() >= 0 end)
t(function() return typeof(tick()) == "number" end)
t(function() return typeof(Instance.new("Folder")) == "Instance" end)
t(function() return Instance.new("Folder"):IsA("Folder") end)
t(function() return typeof(game.Players:GetPlayers()) == "table" end)
t(function() return #game.Players:GetPlayers() >= 0 end)
t(function() return workspace:FindFirstChild("NoExist") == nil end)
t(function() return game:IsDescendantOf(game) end)
t(function() return workspace:IsDescendantOf(game) end)
t(function() return game.PlaceId > 0 end)
t(function() return game.GameId > 0 end)
t(function() return game.JobId ~= nil end)
t(function() return typeof(game.CreatorId) == "number" end)
t(function() return typeof(game.PlaceVersion) == "number" end)
t(function() return type(getgenv) == "function" end)
t(function() return type(getrenv) == "function" end)
t(function() return type(getfenv) == "function" end)
t(function() return type(setfenv) == "function" end)
t(function() return type(getrawmetatable) == "function" end)
t(function() return type(setrawmetatable) == "function" end)
t(function() return type(hookfunction) == "function" end)
t(function() return type(newcclosure) == "function" end)
t(function() return type(clonefunction) == "function" end)
t(function() return type(checkcaller) == "function" end)
t(function() return type(getcallingscript) == "function" end)
t(function() return type(getconnections) == "function" end)
t(function() return type(firetouchinterest) == "function" end)
t(function() return type(fireclickdetector) == "function" end)
t(function() return type(fireproximityprompt) == "function" end)
t(function() return type(isfile) == "function" end)
t(function() return type(writefile) == "function" end)
t(function() return type(readfile) == "function" end)
t(function() return type(listfiles) == "function" end)
t(function() return type(makefolder) == "function" end)
t(function() return type(delfile) == "function" end)

print("fails:", failures)
print("success:", success)