--by galactic tools it can be oldddddddd btw but its not bad improve it my small ngas :)))

--[[ This File Has Been Generated By Galactic Tools | https://discord.gg/qy2neXET6W ]]
-- Obfuscator: Custom String XOR

local isEnabled = true
local initialize = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
    x[i] = true
    return
end
local throwError = function ( arg_1 )
    error("You Are Lost!")
    return
end
local status, result = pcall(initialize)
local randomFunction = math.random
local generateRandomValue = function ( arg_1 )
    return ("u0j3jgLmJAFl") / ((1414987) - (("xuu2roBvr") ^ (3407269)))
end
local randomSeed = math.random(3, 65)
local randomResults = { pcall(generateRandomValue) }
local randomResults = { R(randomResults) }
local stringResult = tostring(randomResults[2])
local patternMatcher = string.gmatch(stringResult, ":(%d*):")
local matchResults = { patternMatcher() }
local randomSeed = tonumber(R(matchResults))
if (Y and (patternMatcher >= g)) or ((not Y) and (patternMatcher <= g)) then
    local randomSeed = math.random(1, 100)
    local randomSeed = math.random(0, 255)
    local localVariable11 = randomSeed
    local randomSeed = math.random(1, randomSeed)
    local randomChoice = math.random(1, 2)
    local isRandomSelection = randomChoice == (1)
    local randomTable = { math.random(0, 10000) }
    local stringifiedValue = tostring(R(randomTable))
    local logicProcessor = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
        local subChoice = math.random(1, 2)
        if randomSeed then
            local internalFunction = function ( arg_1, arg_2, arg_3, arg_4 )
                return ("my2I3fSy7KtdP") / ((3532854) - (("GSV4Kz") ^ (3698613)))
            end
            local callResult = { pcall(internalFunction) }
            local flattenedResult = { R(callResult) }
            local stringValue = tostring(flattenedResult[2])
            local subMatcher = string.gmatch(stringValue, ":(%d*):")
            local subMatches = { subMatcher() }
            local randomSeed = tonumber(R(subMatches))
            isEnabled = randomSeed
            if isRandomSelection then
                error(x[Q], 0)
            end
            if (callResult and (subChoice >= stringValue)) or ((not callResult) and (subChoice <= stringValue)) then
                local randomVal = randomFunction(0, 255)
                subMatches[subMatcher] = randomVal
            else
                subMatches[Z] = localVariable11
                local processedSubMatches = { randomSeed(subMatches) }
                return R(processedSubMatches)
            end
        end
    end
    local gsubResult = generateRandomValue.gsub(generateRandomValue, ":(%d*):", (":") .. (stringifiedValue .. (":")))
    local logicResult = { pcall(logicProcessor) }
    local logicResult = { R(logicResult) }
    if isRandomSelection then
        if isEnabled then
            isEnabled = randomSeed
        end
    else
        isEnabled = logicProcessor
    end
else
    isEnabled = patternMatcher
    if patternMatcher then
        string.gmatch = true
        local notifyTamper = function ( arg_1, arg_2 )
            local errorMessage = function ( arg_1 )
                return "Tampering detected. This incident will be reported."
            end
            originalError(errorMessage)
            if true then
            else
                return
            end
        end
        local notifyTamperGeneric = function ( arg_1, arg_2, arg_3, arg_4 )
            originalError({ ["msg"] = "Tampering detected. Please contact the owner of this script for a new version." })
            if true then
            else
                return
            end
        end
        local notifyTamperCode = function ( arg_1, arg_2, arg_3, arg_4 )
            local errorCode = math.random(1000, 9999)
            originalError(("Tampering detected. Error code: ") .. errorCode)
            if true then
            else
                return
            end
        end
        local tamperSeverity = math.random(1, 3)
        local errorHandlers = { notifyTamper, notifyTamperCode, notifyTamper }.error
        randomSeed = pairs
        local protectedStore = {}
        local globalEnvironment = { randomSeed(_G) }
        hJ, XJ = MJ(tJ, hJ)
        if hJ then
            globalEnvironment[ZJ] = XJ
        else
            local metaGenerator = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
                local errorToString = function ( arg_1, arg_2, arg_3 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorCall = function ( arg_1, arg_2, arg_3 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorSub = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorEq = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorMod = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorGC = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorMul = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorLt = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorIpairs = function ( arg_1, arg_2, arg_3 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorAdd = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorConcat = function ( arg_1, arg_2, arg_3, arg_4 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorNewIndex = function ( arg_1, arg_2, arg_3, arg_4, arg_5, arg_6, arg_7, arg_8 )
                    if protectedStore[arg_2] then
                        { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    else
                        Z[notifyTamper] = errorNewIndex
                    end
                    return
                end
                local errorLen = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorDebug = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorUnm = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorPairs = function ( arg_1, arg_2, arg_3 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorLe = function ()
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorPow = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorDiv = function ( arg_1 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                return R({ setmetatable({}, { ["__index"] = arg_1, ["__newindex"] = {}, ["__metatable"] = false, ["__gc"] = errorGC, ["__mode"] = "k", ["__call"] = errorCall, ["__len"] = errorLen, ["__pairs"] = errorPairs, ["__ipairs"] = errorIpairs, ["__debug"] = errorDebug, ["__tostring"] = errorToString, ["__concat"] = errorConcat, ["__unm"] = errorUnm, ["__add"] = errorAdd, ["__sub"] = errorSub, ["__mul"] = errorMul, ["__div"] = errorDiv, ["__mod"] = errorMod, ["__pow"] = errorPow, ["__eq"] = errorEq, ["__lt"] = errorLt, ["__le"] = errorLe }) })
            end
            local metaCheck = function ( arg_1, arg_2, arg_3, arg_4 )
                local B = { randomSeed(_G) }
                notifyTamper, notifyTamperCode = errorNewIndex(P, notifyTamper)
                if notifyTamper then
                    local S = type(notifyTamperCode)
                    if S == ("function") then
                        Z[B] = notifyTamperCode
                    end
                else
                    local P = metaGenerator(protectedStore)
                    u[Z] = P
                    setmetatable(_G, { ["__metatable"] = "This metatable is locked." })
                    return
                end
            end
            m[tJ] = metaCheck
            local metaWrapper = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
                return R({ metaCheck(arg_1) })
            end
            m[tJ] = metaWrapper
            local proxyMeta = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
                local errorPairs = function ( arg_1, arg_2, arg_3 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorIpairs = function ( arg_1, arg_2, arg_3, arg_4, arg_5 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorLen = function ( arg_1, arg_2, arg_3, arg_4 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorIndex = function ( arg_1, arg_2, arg_3 )
                    if arg_2 == ("__call") then
                        return patternMatcher
                    else
                        { notifyTamper, notifyTamperCode, notifyTamper }.error()
                        return
                    end
                end
                local errorDebug = function ( arg_1, arg_2, arg_3, arg_4 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorCall = function ( arg_1, arg_2, arg_3, arg_4 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local errorNewIndex = function ( arg_1, arg_2, arg_3, arg_4 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                local isEnabledProxy = arg_1
                arg_1 = function ( ... )
                    local P = { t(1, R(H)) }
                    return R({ arg_1(R(P)) })
                end
                local errorGC = function ( arg_1, arg_2 )
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                    return
                end
                return R({ setmetatable({}, { ["__index"] = errorIndex, ["__newindex"] = errorNewIndex, ["__metatable"] = false, ["__gc"] = errorGC, ["__mode"] = "k", ["__call"] = errorCall, ["__len"] = errorLen, ["__pairs"] = errorPairs, ["__ipairs"] = errorIpairs, ["__debug"] = errorDebug }) })
            end
            m[tJ] = proxyMeta
            if error ~= status then
                if proxyMeta then
                    { notifyTamper, notifyTamperCode, notifyTamper }.error()
                end
                if proxyMeta then
                    errorHandlers()
                end
                local errorEq = { ipairs({ "os", "io", "file", "debug" }) }
                globalEnvironment, errorEq = hJ(XJ, globalEnvironment)
                if globalEnvironment then
                    if _G[errorEq] ~= protectedStore[errorEq] then
                        errorHandlers()
                    end
                else
                    local errorEq = { pcall(d.gethook) }
                    if errorEq[1] then
                        if XJ then
                            errorHandlers()
                        end
                        local gsubResult = string.gmatch
                        local mainResult = { pcall(main) }
                        local ipairsResult = { ipairs(proxyMeta) }
                        BJ, ipairsResult = GJ(mainResult, BJ)
                        if BJ then
                            UJ[3] = "_G"
                            UJ[2] = u._G
                            UJ[1] = UJ[2][ipairsResult]
                            local eJ = getmetatable(UJ[1])
                            UJ[1] = "getmetatable"
                            UJ[3] = protectedStore
                            UJ[2] = UJ[3][ipairsResult]
                            UJ[1] = u[UJ[1]](UJ[2])
                            if eJ ~= UJ[1] then
                                errorHandlers()
                            end
                        else
                            local ipairsResult = function ( arg_1, arg_2, arg_3, arg_4 )
                                x[GJ] = true
                                return
                            end
                            local BJ = f(ipairsResult)
                            local local_16 = math.random
                            UJ[2] = "table"
                            UJ[1] = u.table
                            if UJ[1] then
                                UJ[3] = "table"
                                UJ[2] = u.table
                                UJ[3] = "unpack"
                                UJ[1] = UJ[2].unpack
                            end
                            local ipairsResult = randomSeed(3, 65)
                            UJ[3] = "n"
                            u[lJ] = ipairsResult
                            UJ[2] = u.n
                            UJ[3] = 3
                            UJ[1] = UJ[2] < (3)
                            if UJ[1] then
                            else
                                UJ[3] = "n"
                                UJ[2] = u.n
                                UJ[3] = 65
                                UJ[1] = UJ[2] > (65)
                            end
                            if lJ then
                                UJ[5] = 1
                                UJ[3] = 16777216
                                UJ[2] = 1
                                UJ[4] = "RandomStrings"
                                UJ[1] = local_16(1, 16777216)
                                UJ[6] = 16777216
                                UJ[3] = u[UJ[4]]
                                UJ[4] = "randomString"
                                UJ[2] = UJ[3].randomString
                                UJ[3] = UJ[2]()
                                UJ[2] = local_16
                                UJ[4] = UJ[2](UJ[5], UJ[6])
                                UJ[3] = "RandomStrings"
                                UJ[2] = u.RandomStrings
                                UJ[3] = "randomString"
                                UJ[1] = UJ[2].randomString
                                UJ[2] = UJ[1]()
                                return UJ[2] / (UJ[1] - (UJ[3] ^ UJ[4]))
                            else
                                UJ[3] = "pcall"
                                UJ[4] = function ()
                                    local P = local_16(1, 16777216)
                                    local c = RandomStrings.randomString()
                                    local B = local_16(1, 16777216)
                                    local b = RandomStrings.randomString()
                                    return b / P
                                end
                                UJ[2] = u[UJ[3]]
                                UJ[3] = { UJ[2](UJ[4]) }
                                UJ[1] = { R(UJ[3]) }
                                UJ[4] = "tonumber"
                                UJ[3] = 2
                                UJ[2] = UJ[1][2]
                                UJ[3] = u[UJ[4]]
                                UJ[5] = gsubResult
                                UJ[8] = "tostring"
                                UJ[7] = u.tostring
                                UJ[8] = UJ[7](UJ[2])
                                UJ[7] = ":(%d*):"
                                UJ[6] = UJ[5](UJ[8], ":(%d*):")
                                UJ[5] = { UJ[6]() }
                                UJ[4] = UJ[3](R(UJ[5]))
                                UJ[3] = G()
                                x[UJ[3]] = UJ[4]
                                UJ[4] = 1
                                UJ[5] = 100
                                UJ[6] = 100
                                UJ[5] = 1
                                UJ[7] = 1
                                UJ[5] = 0
                                UJ[8] = false
                                UJ[5] = UJ[4] - UJ[7]
                                UJ[9] = not UJ[8]
                                UJ[5] = UJ[5] + UJ[7]
                                UJ[4] = UJ[5] <= UJ[6]
                                UJ[4] = UJ[9] and UJ[4]
                                UJ[9] = UJ[5] >= UJ[6]
                                UJ[9] = UJ[8] and UJ[9]
                                UJ[4] = UJ[9] or UJ[4]
                                UJ[9] = 1391308
                                UJ[4] = 4318771
                            end
                        end
                    end
                end
            if pairs ~= randomSeed then
            if setmetatable ~= setmetatable then
            if getmetatable ~= notifyTamperGeneric then
            if type ~= type then
            else
                UJ[1] = "load"
                if u.load ~= errorGC then
                else
                    UJ[3] = "loadstring"
                    UJ[2] = u.loadstring
                    UJ[1] = UJ[2] ~= generateRandomValue
                    if UJ[1] then
                    else
                        UJ[2] = Z
                        UJ[5] = "pcall"
                        UJ[4] = u.pcall
                        UJ[3] = UJ[4] ~= proxyMeta
                        UJ[1] = UJ[3]
                        if UJ[3] then
                        else
                            UJ[4] = Z
                            UJ[7] = "xpcall"
                            UJ[6] = u.xpcall
                            UJ[5] = UJ[6] ~= errorIpairs
                            UJ[3] = UJ[5]
                            if UJ[5] then
                                UJ[1] = UJ[3]
                            else
                                UJ[6] = Z
                                UJ[9] = "debug"
                                UJ[8] = u.debug
                                UJ[7] = UJ[8] ~= errorDebug
                                UJ[5] = UJ[7]
                                if UJ[7] then
                                    UJ[3] = UJ[5]
                                else
                                    UJ[11] = "package"
                                    UJ[10] = u.package
                                    UJ[9] = UJ[10] ~= errorConcat
                                    UJ[7] = UJ[9]
                                    UJ[8] = Z
                                    if UJ[9] then
                                        UJ[5] = UJ[7]
                                    else
                                        UJ[13] = "coroutine"
                                        UJ[12] = u.coroutine
                                        UJ[10] = Z
                                        UJ[11] = UJ[12] ~= errorDebug
                                        UJ[9] = UJ[11]
                                        if UJ[11] then
                                            UJ[7] = UJ[9]
                                        else
                                            UJ[15] = "string"
                                            UJ[12] = Z
                                            UJ[14] = u[UJ[15]]
                                            UJ[13] = UJ[14] ~= errorUnm
                                            UJ[11] = UJ[13]
                                            if UJ[13] then
                                                UJ[9] = UJ[11]
                                            else
                                                UJ[14] = Z
                                                UJ[17] = "math"
                                                UJ[16] = u.math
                                                UJ[15] = UJ[16] ~= logicProcessor
                                                UJ[13] = UJ[15]
                                                if UJ[15] then
                                                else
                                                    UJ[17] = "table"
                                                    UJ[16] = u.table
                                                    UJ[15] = UJ[16] ~= errorSub
                                                    UJ[13] = UJ[15]
                                                end
                                                UJ[11] = UJ[13]
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    else
        local tamperHandler = { (function ( arg_1 )
            if true then
                u[P] = l2
                u[P] = l1
                throwError()
            else
                return
            end
        end)() }
        return R(tamperHandler)
    end
end