local ProjectDiamondSound = Instance.new("Sound")
        if pcall(function() ProjectDiamondSound.PlaybackLoudness = 69 end) then
            error("detected!!! BY PROJECT DIAMOND!!! https://discord.gg/X8Y2JmxJCZ")
return nil
        end
        ProjectDiamondSound:Destroy()

        local ProjectDiamondTb = Instance.new("TextBox")
        if pcall(function() ProjectDiamondTb.TextBounds = Vector2.new(67,67) end) then
            error("detected!!! https://discord.gg/X8Y2JmxJCZ")
        end
        ProjectDiamondTb:Destroy()

		print("pass")