-- By LeakD - discord.gg/qteAQmfJmP


local LeakD1 = pcall(function()
	local LeakD2 = game:GetService("CoreGui")
	if LeakD2 == nil then error("LeakD Is Best", 2) end
	local LeakD3 = LeakD2:WaitForChild("RobloxGui", 5)
	if LeakD3 == nil then error("LeakD Is Best", 2) end
	local LeakD4 = LeakD3:WaitForChild("Modules", 5)
	if LeakD4 == nil then error("LeakD Is Best", 2) end
	local LeakD5 = LeakD4:WaitForChild("Settings", 5)
	if LeakD5 == nil then error("LeakD Is Best", 2) end
	local LeakD6 = LeakD5:WaitForChild("Pages", 5)
	if LeakD6 == nil then error("LeakD Is Best", 2) end
	local LeakD7 = LeakD6:WaitForChild("Help", 5)
	if LeakD7 == nil then error("LeakD Is Best", 2) end
end)
if not LeakD1 then error("LeakD Is Best", 2) end

print("pass")